name: JSBoiler
version: 0.1.0.0
license: GPL-3
license-file: LICENSE
author: Kristiyan Tsaklev
maintainer: cuki@cukii.me
category: Language

dependencies:
- base
- text

library:
  source-dirs: src
  dependencies:
  - unordered-containers
  - megaparsec
  - transformers
  - template-haskell
  ghc-options:
  - -Wall
  - -Werror

executables:
  boiler:
    main: Main.hs
    source-dirs: app
    dependencies:
    - JSBoiler
    ghc-options:
    - -Wall
    - -Werror

tests:
  boiler-tests:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - megaparsec
    - hspec
    - JSBoiler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
